application:
  name: simple-example-node-with-postgresql
  project: nodejsanddb
  publicly_accessible: true
databases:
- type: postgresql
  version: "12"
  name: my-psql
routers:
- name: main
  routes:
  - application_name: simple-example-node-with-postgresql
    paths:
    - /
