---
application:
  name: "simple-example-node-with-postgresql"
  project: "myproject"
  organization: "QoveryCommunity"
routers:
- name: "main-simple-example-node-with-postgresql"
  routes:
  - application_name: "simple-example-node-with-postgresql"
    paths:
    - "/*"
